import os
import sys
import json
import requests
from dotenv import load_dotenv
from openai import OpenAI

# Load environment variables
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

# Environment Keys
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
SPOONACULAR_API_KEY = os.environ.get("SPOONACULAR_API_KEY", "")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")

openai_client = OpenAI(api_key=OPENAI_API_KEY)

def layer1_spoonacular(restaurant_name: str) -> str:
    """LAYER 1: The Database. Instant, mathematically precise ingredient arrays."""
    if not SPOONACULAR_API_KEY:
        print("🟡 LAYER 1 SKIPPED: Missing SPOONACULAR_API_KEY")
        return ""
        
    print(f"🟢 LAYER 1 ACTIVE: Querying Spoonacular for {restaurant_name}...")
    try:
        # Step 1: Search for the restaurant menu items
        search_url = f"https://api.spoonacular.com/food/menuItems/search?query={restaurant_name}&number=10&apiKey={SPOONACULAR_API_KEY}"
        search_resp = requests.get(search_url, timeout=5).json()
        menu_items = search_resp.get("menuItems", [])
        
        if not menu_items:
            print("🟡 LAYER 1 FAILED: Restaurant not found in database.")
            return ""
            
        compiled_text = f"SPOONACULAR OFFICIAL DATA FOR {restaurant_name}:\n"
        for item in menu_items:
            # Step 2: Grab the exact ingredients for each item id
            item_id = item.get("id")
            info_url = f"https://api.spoonacular.com/food/menuItems/{item_id}?apiKey={SPOONACULAR_API_KEY}"
            info_resp = requests.get(info_url, timeout=5).json()
            # Some items might only have nutrition, no explicit string of 'ingredients' depending on spoonacular data structure, varying wildly
            # Spoonacular usually provides a list of badges/nutrition but sometimes raw ingredients.
            nutrition_context = json.dumps(info_resp.get('nutrition', {})) 
            compiled_text += f"- Dish: {item.get('title')} | Macros: {nutrition_context}\n"
            
        return compiled_text
    except Exception as e:
        print(f"❌ LAYER 1 ERROR: {e}")
        return ""


def layer2_perplexity(restaurant_name: str, location: str) -> str:
    """LAYER 2: The Live Drone. Uses Perplexity via OpenRouter to bypass Cloudflare and scrape exact PDFs."""
    if not OPENROUTER_API_KEY:
        print("🔵 LAYER 2 SKIPPED: Missing OPENROUTER_API_KEY")
        return ""
        
    print(f"🔵 LAYER 2 ACTIVE: Deploying Perplexity Web Drone for {restaurant_name} {location}...")
    try:
        openrouter_client = OpenAI(api_key=OPENROUTER_API_KEY, base_url="https://openrouter.ai/api/v1")
        response = openrouter_client.chat.completions.create(
            model="perplexity/llama-3.1-sonar-huge-128k-online",
            messages=[
                {"role": "system", "content": "You are an investigative drone. Your sole directive is to browse the internet, locate the OFFICIAL allergen/ingredient list (often a PDF or hidden sub-page) for the requested restaurant, and extract the EXACT text of the ingredients. Do NOT format as JSON. Just dump the raw unedited ingredient text of the menu."},
                {"role": "user", "content": f"Find the official exact ingredient list for the restaurant: {restaurant_name} (near {location}). Search their official website or menustat.org."}
            ],
            timeout=30
        )
        data = response.choices[0].message.content
        if "not find" in data.lower() or "do not have" in data.lower():
            print("🟡 LAYER 2 FAILED: Drone could not locate proprietary data on the open web.")
            return ""
        return f"PERPLEXITY LIVE-WEB SCRAPE DATA:\n{data}"
    except Exception as e:
        print(f"❌ LAYER 2 ERROR: {e}")
        return ""


def layer3_gpt4o_compile(restaurant_name: str, context: str, profiles: list, used_source: str) -> dict:
    """LAYER 3: The Brain. Takes context from Layer 1/2, or falls back to Commercial Baseline Synthesis if empty."""
    print(f"🟠 OVERARCHING BRAIN: Booting GPT-4o JSON Compiler (Data Source: {used_source})")
    
    # If both APIs failed or missing keys, force standard synthesis.
    if not context.strip():
        used_source = "COMMERCIAL_SYNTHESIS"
        print("🟠 LAYER 3 ACTIVE: Falling back strictly to Commercial Baseline Synthesis.")
        context = "NO OFFICIAL DATA ACQUIRED. YOU MUST SYNTHESIZE COMMERCIAL BASELINES."
        
    system_prompt = f"""
    You are an elite Food Science API designed to protect patients with severe Monosodium Glutamate intolerances.
    
    You have been provided with background context generated by upstream data acquisition layers.
    DATA ACQUISITION SOURCE: {used_source}
    BACKGROUND CONTEXT: {context}

    THE ABSOLUTE MSG CHEMICAL DATABASE (Identify all loopholes):
    - [TIER 1] GUARANTEED MSG: Monosodium Glutamate (E621), Yeast Extract, Autolyzed Yeast, Hydrolyzed Veg/Soy Protein, Calcium Caseinate, Torula Yeast.
    - [TIER 2] HIGH PROBABILITY: Natural Flavors, Artificial Flavors, Bouillon, Broth, Maltodextrin, Pectin, Soy Sauce.
    - [TIER 3] ENHANCERS: Disodium 5'-guanylate, Disodium 5'-inosinate.
    
    CRITICAL BEHAVIORAL RULES:
    1. STRICT INGREDIENT REPORTING: You must provide a literal mathematical array of ALL common ingredients comprising the dish under the 'ingredients' array.
    2. THE "COMMERCIAL BASELINE" SYNTHESIS: If the BACKGROUND CONTEXT indicates "NO OFFICIAL DATA ACQUIRED", you must act as an INDUSTRIAL FOOD SCIENTIST. Populate the 'ingredients' array with the exact, standard commercial supply-chain formulation typically used for that dish (e.g. for a Turkey Sub, list Water, Salt, Dextrose, Carrageenan, Natural Flavors, etc.).
    3. ASSIGN THE SOURCE ENUM: Set 'ingredient_source' exactly matching the provided DATA ACQUISITION SOURCE: "{used_source}".
    4. NO VAGUE HEDGING: You are strictly forbidden from writing paragraphs like "Typically includes...". The UI renders the 'ingredients' array as chemical chips.
    5. CULINARY INFERENCE: Explain which specific additives from the 'ingredients' array match the MSG Danger Tiers. 
    6. OUTPUT DENSITY: Generate a minimum of 15-20 realistic menu items for restaurants, including safe baselines like plain rice or plain beef patties.
    """

    final_output_schema = {
        "type": "json_schema",
        "json_schema": {
            "name": "analysis_results",
            "strict": True,
            "schema": {
                "type": "object",
                "properties": {
                    "telemetry": {
                        "type": "object",
                        "properties": {
                            "chars_scraped": {"type": "integer"},
                            "urls_crawled": {"type": "integer"},
                            "chemicals_checked": {"type": "integer"}
                        },
                        "required": ["chars_scraped", "urls_crawled", "chemicals_checked"],
                        "additionalProperties": False
                    },
                    "restaurant": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string"},
                            "search_context": {"type": "string"}
                        },
                        "required": ["name", "search_context"],
                        "additionalProperties": False
                    },
                    "results": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "dish_name": {"type": "string"},
                                "status": {"type": "string", "enum": ["SAFE", "UNSAFE", "UNKNOWN"]},
                                "flagged_by": {
                                    "type": "array",
                                    "items": {"type": "string"}
                                },
                                "ingredient_source": {
                                    "type": "string",
                                    "enum": ["SPOONACULAR_DB", "PERPLEXITY_LIVE_SCRAPE", "COMMERCIAL_SYNTHESIS", "OFFICIAL_SCRAPE"]
                                },
                                "ingredients": {
                                    "type": "array",
                                    "description": "The exact corporate ingredients, or your synthesized commercial baseline list.",
                                    "items": {"type": "string"}
                                },
                                "culinary_inference": {"type": "string"},
                                "confidence": {"type": "string", "enum": ["HIGH", "LOW"]}
                            },
                            "required": ["dish_name", "status", "flagged_by", "ingredient_source", "ingredients", "culinary_inference", "confidence"],
                            "additionalProperties": False
                        }
                    },
                    "disclaimer": {"type": "string"}
                },
                "required": ["telemetry", "restaurant", "results", "disclaimer"],
                "additionalProperties": False
            }
        }
    }

    try:
        response = openai_client.chat.completions.create(
            model="gpt-4o",
            temperature=0.1,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Compile the final json payload for {restaurant_name} using the context provided."}
            ],
            response_format=final_output_schema
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"❌ Layer 3 Brain Failure: {e}")
        return {}


def analyze_allergens(restaurant_name: str, location: str, profiles: list) -> dict:
    source_tag = "UNKNOWN"
    context = ""
    
    # Layer 1
    context = layer1_spoonacular(restaurant_name)
    if context:
        source_tag = "SPOONACULAR_DB"
    
    # Layer 2
    if not context:
        context = layer2_perplexity(restaurant_name, location)
        if context:
            source_tag = "PERPLEXITY_LIVE_SCRAPE"
            
    # Layer 3 / Final Compilation
    if not context:
        source_tag = "COMMERCIAL_SYNTHESIS"
        
    payload = layer3_gpt4o_compile(restaurant_name, context, profiles, source_tag)
    
    # Mock telemetry
    if payload.get("telemetry"):
        payload["telemetry"]["chars_scraped"] = len(context)
        payload["telemetry"]["urls_crawled"] = 1 if source_tag == "SPOONACULAR_DB" else (5 if source_tag == "PERPLEXITY_LIVE_SCRAPE" else 0)
        
    return payload


if __name__ == "__main__":
    test_profiles = [
        {"name": "MSG Scanner", "restrictions": ["MSG-Free"]}
    ]
    print("Initiating 3-Layer Architecture Test...")
    res = analyze_allergens("Jersey Mikes", "Oregon", test_profiles)
    print("\n📦 COMPILED RESULTS (First 1 items):\n", json.dumps(res.get("results", [])[:1], indent=2))
